parameters:
    app.mail.from: '%env(APP_MAIL_FROM)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $mailFrom: '%app.mail.from%'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # App\Service\QuoteGenerator:
    #     arguments:
    #         $mailFrom: '%app.mail.from%'


